name: speedyship
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  cloud_firestore: ^4.5.2
  file_picker: ^5.3.0
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.1
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.0
  image_picker: ^0.8.7+4
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - lib/images/
